### ISSUE TITLE
"rigth-click", "double-click" and "drap-drop"

### ISSUE THREAD

**Issue by crfnunes** [christianrondeau/SikuliSharp#10]
Hi there, thanks for this wrapper.

Is possible to include other commands, like "rigth-click", "double-click" and "drap-drop"?
Thank you!

**Comment by christianrondeau** [comment]
Hi! It is possible, though I won't be able to put time in this in the very short term. If you want to add the feature, it should be fairly simple. You would first need to check in [Sikuli](http://doc.sikuli.org/) how to do it, and then you can add a new method to [SikuliSession.cs](https://github.com/christianrondeau/SikuliSharp/blob/master/SikuliSharp/SikuliSession.cs#L32) that simply calls the matching Sikuli command. Feel free to send a pull request :)

**Comment by mnkjadhav** [comment]
Fix for this issue is submitted and it is available in v1.4.0
