### ISSUE TITLE
Always get System.TimeoutExceptions: No result in alloted time

### ISSUE THREAD

**Issue by hmsulehri** [christianrondeau/SikuliSharp#11]
@christianrondeau 

Hi, I always get the timeout exception, when try to run a SikuliSession, below is the stack trace.

**StackTrace:**
           AsyncTwoWayStreamHaldler.ReadUntil(Double timeoutInSeconds, String[] expectedStrings)
           SikuliRuntime.Start()
           Sikuli.CreateSession()

Any idea how to solve this issue.

Best Regards.

**Comment by christianrondeau** [comment]
A few things that would help :

1. What does your actual script looks like? 
2. Does Sikuli itself works?

**Comment by hmsulehri** [comment]
1. Following is my Test script

```
public void SikuliSharpTest()
        {
            using (var session = Sikuli.CreateSession())
            {
                var txtLoginUsername = Patterns.FromFile(@"C:\Users\hamidm\Documents\Visual Studio 2015\Projects\Anoto.Automation\Web\Images\loginUsername.png");

                Assert.IsTrue(session.Exists(txtLoginUsername, 5));

                session.Click(txtLoginUsername);
                session.Type("hamid.mahmood@anoto.com");
            }
```

2. Yes, I can run the Sikuli IDE, and create and run scripts from there.

**Comment by christianrondeau** [comment]
Either the username is not found, or there a config error..  Can you build from source using the debug build configuration, and run your script? The answer should be in the visual studio output window.

**Comment by hmsulehri** [comment]
Is it must to have sikuli-script.jar in my sikuli installation folder? If yes, then I don't have that jar in my Sikuli installation.

**Comment by christianrondeau** [comment]
Correct, you maybe did not install the "correct" Sikuli options. See https://github.com/christianrondeau/SikuliSharp/blob/master/README.md
