### ISSUE TITLE
Issue when using Session.Click(pattern, timeout) function with timeout > 0f

### ISSUE THREAD

**Issue by tanakashiro** [christianrondeau/SikuliSharp#12]
Hi,
I have a quick look in the code and see that it maybe something wrong for this
[code]
		protected bool RunCommand(string command, IPattern pattern, float timeoutInSeconds)
		{
			pattern.Validate();

			var script = string.Format(
				"print \"SIKULI#: YES\" if {0}({1}{2}) else \"SIKULI#: NO\"",
				command,
				pattern.ToSikuliScript(),
				AddTimeout(timeoutInSeconds)
				);
               ...
               }
[code]
This will ad a key modifier code into click function in stead of a timeout for click action.
Please help me check.

**Comment by christianrondeau** [comment]
Ah, you are correct! The `click`'s 2nd parameter is a modified, not a timeout! Actually, I don't think "click" even supports a timeout. This is indeed a bug, though in practice you can simply *not* provide a timeout and it'll work. I'll mark this as a defect, thanks!

**Comment by christianrondeau** [comment]
I "fixed" the timeout issues on these methods by... removing the timeout parameter :)
