### ISSUE TITLE
Issue when using Session.<some action as Click, Wait...>(pattern) without specify timeout

### ISSUE THREAD

**Issue by tanakashiro** [christianrondeau/SikuliSharp#15]
Hi christianrondeau,
I have some doubt that when I run the code as below if the pattern cannot be found, my test application seem hangs in this state and cannot process to next action.
Session.Click(pattern);
I expected that it would return "SIKULI# : NO" as the script you specified for run in the RunCommand functions but it would not, after do some checks I found that some sikuli actions like "click","wait","exists"... would throw an exception FindFailed if the pattern cannot be found on the screen instead of return anything, that maybe the cause why the RunCommand function would not return.

Can you help to check this again.

Regards,

**Comment by christianrondeau** [comment]
Can you provide me with a replication procedure? Not all methods actually receive a timeout (see #12) so I might have to change how this works a little bit, I would try and solve both at the same time.

The C# code you use in your test, with a program typically installed (e..g Notepad) would be very helpful.

**Comment by tanakashiro** [comment]
Hi christianrondeau,
I wrote a simple program, which is just for clicking a mozzila FF shortcut on the main screen. If FF is there, the console print "OK" as expected,, but when I hide the shortcut, it never goes to printing the line "NOT_OK" or any lines after the 'click' function.  
`    class Program
    {
        static void Main(string[] args)
        {
            string imgPath = @"D:\TestSikuli\";
            SikuliSharp.ISikuliSession session = SikuliSharp.Sikuli.CreateSession();
            
            bool clickRet = session.Click(Patterns.FromFile(Path.Combine(imgPath, "MOZILLASC.PNG"), 1f));
            if (clickRet)
            {
                Console.WriteLine("OK");
            }
            else
            {
                Console.WriteLine("NOT_OK");
            }
            Console.WriteLine("Press any key to exit....");
            Console.Read();
        }
    }`

**Comment by christianrondeau** [comment]
That's perfect, thanks. I'll look into it (I won't be able to look into it immediately though... I'm rushed with other stuff), as soon as I have some free time I'll try to see what I can do. Your theory is good, if you need this quickly and you feel like trying to provide a PR, here's what should happen:

1. In https://github.com/christianrondeau/SikuliSharp/blob/master/SikuliSharp/SikuliRuntime.cs#L71 detect "one of multiple possible strings", and;
2. https://github.com/christianrondeau/SikuliSharp/blob/master/SikuliSharp/SikuliSession.cs#L89 should provide the different possible "stop" strings it can expect (e.g. "Error:" or "Exception")

To know what Sikuli actually returns, the simplest way is to build SikuliSharp in Debug mode, you'll see the command output prefixed with `Sikuli>` in the console.

Hope that helps!

**Comment by christianrondeau** [comment]
Actually, it looks like it should already do this: https://github.com/christianrondeau/SikuliSharp/blob/master/SikuliSharp/SikuliRuntime.cs#L22 (see `ErrorMarker`) - I think maybe the error marker changed. Run SikuliSharp in Debug mode and you'll see what it is now.

**Comment by tanakashiro** [comment]
Hi Chris,
Currently I could not see any return message even if I run in Debug mode in this case, is there any failure in my configuration ?.
By the way, I found this on Sikuli Document side :
"By default, if the visual object (image or text) cannot be found, Sikuli will stop the script by raising an Exception FindFailed. This follows the standards of the Python language, so that you could handle such exceptions using try: ... except: ...."
I think you should consider to handle this in the script Jython in SikuliSession.cs.
I have tried the work around here and it worked in this case, need more check in others.

Hope this helpful !

**Comment by christianrondeau** [comment]
Thanks, that helps. I have some time to look at it, I see two things;

1. The error stream is not read, so you won't see anything in the console
2. As you have said, because it won't read the error stream, it won't see there was an error and SikulSharp will wait for Sikuli, and vice-versa :)

Let me see if I can find a quick and elegant solutio.

**Comment by christianrondeau** [comment]
I just pushed some changes that should give you the Sikuli error in the exception message thrown by a failed check. So now, it won't wait forever, *and* it will give you a useful error message!

Let me know if that helps.

**Comment by tanakashiro** [comment]
Hi Chris,
I have tried your changes and it works OK for my cases. I saw that it is great in your solution to separate tasks for reading output and error streams. Thank you for your kind support.
===================================================
1 more issue I see but I think dont need to post in another thread, that could be a minor bug, field SikuliRuntime::_isRunning is not initialized as well as controlled when you start a runtime project but used for checking when stop, this makes the runtime still remain after one time run instead of it should be released. Please check it.

Regards,

**Comment by christianrondeau** [comment]
Fixed it too, thanks! Released on NuGet, v1.2.0!
