### ISSUE TITLE
Click at location is not available

### ISSUE THREAD

**Issue by mnkjadhav** [christianrondeau/SikuliSharp#17]
I want to click at specific Point on screen. But click at location is not available. Is there way to achieve it using SikuliSharp?

**Comment by christianrondeau** [comment]
I see you got the idea :) In the end, we're simply outputting Jython, and your implementation is elegant :) IPattern and ILocation could potentially both be the same ISikuliScript interface to make it easier to extend similar stuff in the future.

**Comment by mnkjadhav** [comment]
Yeah... can do that. I am working on hybrid automation framework for CAD software using Selenium and Sikuli. I have used Sikuli in Jython but this framework requires in .NET. So as and when required, I would love to add new methods to this wrapper.

**Comment by christianrondeau** [comment]
Got it, merged, and a new version has been deployed on NuGet :) Thanks!
