### ISSUE TITLE
Time out Exception

### ISSUE THREAD

**Issue by jedi0605** [christianrondeau/SikuliSharp#4]
Hay, I just use your SikuliSharp, have some question.
Why I using 
 using (var session = Sikuli.CreateSession())
            {
                var pattern = Patterns.FromFile(@"C:\Patterns\MyPattern.png");
                session.Exists(pattern);
            }

And  Sikuli.CreateSession() will throw time out exception?

**Comment by christianrondeau** [comment]
Hi @jedi0605 - sorry for taking so long to answer, I was away :)

My best guess is that you're running another Sikuli version than `1.0.1`.SikuliSharp waits for Sikuli to emit `... use ctrl-d to end the session` - if this string is not shown, you're going to get this error.

I'll check if I can update Sikuli to the latest version :)

**Comment by christianrondeau** [comment]
Just released support for Sikuli 1.1.0 (as #3 asked for) - let me know if that solves it!

**Comment by christianrondeau** [comment]
I'll close this for now, let me know if you still have trouble.
